---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-spark-lama-data
spec:
  capacity:
    storage: '1000Gi'
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-hdd
  hostPath:
    path: /mnt/ess_storage/DN_1/storage/sber_LAMA/kaggle_used_cars_dataset 
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-lama-data
  namespace: spark-lama-exps
spec:
  volumeName: pv-spark-lama-data
  storageClassName: local-hdd
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: '1000Gi'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mnt-nfs
  namespace: spark-lama-exps
spec:
  volumeName: pv-mnt-nfs
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: '100Gi'
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mnt-nfs
spec:
  capacity:
    storage: '100Gi'
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  hostPath:
    path: /mnt/nfs
    type: Directory
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-tmp
spec:
  capacity:
    storage: '10Gi'
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-hdd
  hostPath:
    path: /mnt/ess_storage/DN_1/storage/sber_LAMA/tmp
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-tmp
  namespace: spark-lama-exps
spec:
  volumeName: pv-tmp
  storageClassName: local-hdd
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: '10Gi'
