---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-spark-lama-data
spec:
  capacity:
    storage: '1000Gi'
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-hdd
  hostPath:
    path: /mnt/ess_storage/DN_1/storage/sber_LAMA/kaggle_used_cars_dataset 
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-lama-data
  namespace: spark-lama-exps
spec:
  volumeName: pv-spark-lama-data
  storageClassName: local-hdd
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: '1000Gi'
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-scripts-shared-vol
spec:
  capacity:
    storage: '10Gi'
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-hdd
  hostPath:
    path: /mnt/ess_storage/DN_1/tmp/scripts-shared-vol
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scripts-shared-vol
  namespace: spark-lama-exps
spec:
  volumeName: pv-scripts-shared-vol
  storageClassName: local-hdd
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: '10Gi'
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-spark-lama-exp-results-vol
spec:
  capacity:
    storage: '10Gi'
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-hdd
  hostPath:
    path: /mnt/ess_storage/DN_1/storage/sber_LAMA/exp-results/
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exp-results-vol
  namespace: spark-lama-exps
spec:
  volumeName: pv-spark-lama-exp-results-vol
  storageClassName: local-hdd
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: '10Gi'
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-spark-lama-ivy2-cache
spec:
  capacity:
    storage: '25Gi'
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-hdd
  hostPath:
    path: /mnt/ess_storage/DN_1/storage/sber_LAMA/ivy2cache/
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-lama-ivy2-cache
  namespace: spark-lama-exps
spec:
  volumeName: pv-spark-lama-ivy2-cache
  storageClassName: local-hdd
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: '25Gi'
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-spark-lama-chkp-data
spec:
  capacity:
    storage: '1000Gi'
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-hdd
  hostPath:
    path: /mnt/ess_storage/DN_1/storage/sber_LAMA/spark_chkp_data/
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-lama-chkp-data
  namespace: spark-lama-exps
spec:
  volumeName: pv-spark-lama-chkp-data
  storageClassName: local-hdd
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: '1000Gi'
